### ISSUE TITLE
SyntaxError: Missing parentheses in call to 'print'

### ISSUE THREAD

**Issue by lestephane** [percolate/iamer#5]
I've been unable to run iamer from a freshly pip install'd iamer instance on a VM where the default Python is Python 3. This is probably a simple thing to fix?

Reproduction
$ iamer dump

Traceback (most recent call last):
  File "/usr/local/bin/iamer", line 7, in <module>
    from iamer.main import main
  File "/usr/local/lib/python3.5/dist-packages/iamer/main.py", line 33
    print "TBD"
              ^
SyntaxError: Missing parentheses in call to 'print'

**Comment by lra** [comment]
yes, looks like someone has to make it compatible with python3.
If you want to chip in, you can run 2to3 against it and fix the obvious stuff, and propose a PR.

**Comment by lestephane** [comment]
I won't have the time to come up with a PR (absolutely no python experience) so I used a workaround:

mkvirtualenv --python=python2 iamdumper
(iamdumper) $ pip install iamer
(iamdumper) $ iamer dump

Maybe that helps someone else.
